config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :friend_profiles do
    resources :matches, only: [:create]
  end
  resources :users, only: [:index] do
    resources :connection_requests, only: [:create]
  end
  resources :connection_requests, only: [] do
    resources :connections, only: [:create]
  end

  # Defines the root path route ("/")
  root "friend_profiles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/connection.rb
# frozen_string_literal: true

class Connection < ApplicationRecord
  belongs_to :from, class_name: "User"
  belongs_to :to, class_name: "User"
end

app/models/connection_request.rb
# frozen_string_literal: true

class ConnectionRequest < ApplicationRecord
  belongs_to :from, class_name: "User"
  belongs_to :to, class_name: "User"
end

app/models/friend_profile.rb
# frozen_string_literal: true

class FriendProfile < ApplicationRecord
  validates :name, :description, presence: true
  belongs_to :user

  has_many :outgoing_matches, class_name: "Match", foreign_key: :from_id,
                              dependent: :destroy, inverse_of: :from
  has_many :incoming_matches, class_name: "Match", foreign_key: :to_id,
                              dependent: :destroy, inverse_of: :to
  has_many :outgoing_matched_profiles, through: :outgoing_matches, source: :to
  has_many :incoming_matched_profiles, through: :incoming_matches, source: :from
end

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  belongs_to :from, class_name: "FriendProfile"
  belongs_to :to, class_name: "FriendProfile"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friend_profiles, dependent: :destroy
  has_many :outgoing_connection_requests, class_name: "ConnectionRequest", foreign_key: :from_id,
                                          dependent: :destroy, inverse_of: :from
  has_many :incoming_connection_requests, class_name: "ConnectionRequest", foreign_key: :to_id,
                                          dependent: :destroy, inverse_of: :to
  has_many :connections, foreign_key: :from_id, dependent: :destroy, inverse_of: :from
  has_many :connected_users, through: :connections, source: :to
  has_many :accessible_friend_profiles, through: :connected_users, source: :friend_profiles
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/connection_requests_controller.rb
# frozen_string_literal: true

class ConnectionRequestsController < ApplicationController
  before_action :authenticate_user!

  def create
    ConnectionRequest.create!(from: current_user, to: User.find(params.fetch(:user_id)))
    redirect_to users_url, notice: "Connection request was sent"
  end
end

app/controllers/connections_controller.rb
# frozen_string_literal: true

class ConnectionsController < ApplicationController
  before_action :authenticate_user!

  def create
    connection_request = current_user.incoming_connection_requests.find(params.fetch(:connection_request_id))
    Connection.create!(from: connection_request.from, to: connection_request.to)
    Connection.create!(from: connection_request.to, to: connection_request.from)
    redirect_to users_url, notice: "You are now connected"
  end
end

app/controllers/friend_profiles_controller.rb
# frozen_string_literal: true

class FriendProfilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @friend_profiles = current_user.friend_profiles
  end

  def show
    @friend_profile = current_user.friend_profiles.find(params[:id])
    @matched_profiles = (@friend_profile.outgoing_matched_profiles + @friend_profile.incoming_matched_profiles).uniq
    @profiles_for_matching = current_user.accessible_friend_profiles - @matched_profiles
  end

  def new
    @friend_profile = current_user.friend_profiles.build
  end

  def edit
    @friend_profile = current_user.friend_profiles.find(params[:id])
  end

  def create
    @friend_profile = current_user.friend_profiles.build(friend_profile_params)

    if @friend_profile.save
      redirect_to friend_profiles_url, notice: "Profile was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @friend_profile = current_user.friend_profiles.find(params[:id])

    if @friend_profile.update(friend_profile_params)
      redirect_to friend_profiles_url, notice: "Profile was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    current_user.friend_profiles.find(params[:id]).destroy
    redirect_to friend_profiles_url, notice: "Profile was successfully removed"
  end

  private

  def friend_profile_params
    params.require(:friend_profile).permit(:name, :description)
  end
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

class MatchesController < ApplicationController
  before_action :authenticate_user!

  def create
    from_friend_profile = current_user.friend_profiles.find(params.fetch(:friend_profile_id))
    to_friend_profile = current_user.accessible_friend_profiles.find(params.fetch(:to_friend_profile_id))

    Match.create!(from: from_friend_profile, to: to_friend_profile)

    redirect_to from_friend_profile, notice: "Match created"
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    users = User.where.not(id: current_user.id)

    outgoing_connection_requests = current_user.outgoing_connection_requests.to_a
    incoming_connection_requests = current_user.incoming_connection_requests.to_a
    connections = current_user.connections.to_a

    @users_with_connections = users.map do |user|
      attach_connections(user, outgoing_connection_requests, incoming_connection_requests, connections)
    end
  end

  private

  def attach_connections(user, outgoing_connection_requests, incoming_connection_requests, connections)
    outgoing = outgoing_connection_requests.find do |connection_request|
      connection_request.to == user
    end

    connection = connections.find do |conn|
      conn.to == user
    end

    incoming = incoming_connection_requests.find do |connection_request|
      connection_request.from == user
    end

    [user, connection, incoming, outgoing]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/friend_profiles/edit.html.erb
<h1>Edit profile</h1>

<ul>
  <% @friend_profile.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

<%= form_for @friend_profile do |f| %>
  <%= f.label :name %> <%= f.text_field :name %>
  <br>
  <%= f.label :description %> <%= f.text_area :description %>
  <br>
  <%= f.submit "Change" %>
<% end %>

app/views/friend_profiles/index.html.erb
<h1>Your friends profiles</h1>

<ul>
	<% @friend_profiles.each do |friend_profile| %>
		<li>
			<%= friend_profile.name %>
      <%= link_to "Show", friend_profile_path(friend_profile) %>
      <%= link_to "Edit", edit_friend_profile_path(friend_profile) %>
      <%= link_to "Remove", friend_profile_path(friend_profile), data: { turbo_method: :delete } %>
    </li>
	<% end %>
</ul>

<%= link_to "Create new profile", new_friend_profile_path %>

app/views/friend_profiles/new.html.erb
<h1>Create new profile</h1>

<ul>
  <% @friend_profile.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

<%= form_for @friend_profile do |f| %>
  <%= f.label :name %> <%= f.text_field :name %>
  <br>
  <%= f.label :description %> <%= f.text_area :description %>
  <br>
  <%= f.submit "Create" %>
<% end %>

app/views/friend_profiles/show.html.erb
<h1>Friend profile - <%= @friend_profile.name %></h1>

<p><%= @friend_profile.description %></p>

<h2>Matched profiles</h2>

<% @matched_profiles.each do |matched_profile| %>
	<li>
		<%= matched_profile.name %>
		<%= matched_profile.description %>
	</li>
<% end %>

<h2>Profiles for matching</h2>

<% @profiles_for_matching.each do |profile_for_matching| %>
  <li>
    <%= profile_for_matching.name %>
    <%= profile_for_matching.description %>
    <%= button_to "Match", friend_profile_matches_path(@friend_profile, to_friend_profile_id: profile_for_matching) %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coupler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <p>
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, 'data-turbo-method': :delete  %>
      <% end %>
    </p>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
	<% @users_with_connections.each do |user, connection, incoming, outgoing| %>
		<li>
		  <%= user.email %>

      <% if connection.present? %>
        Connected
      <% elsif incoming.present? %>
        <%= button_to "Accept", connection_request_connections_path(incoming) %>
      <% elsif outgoing.present? %>
          Sent
      <% else %>
        <%= button_to "Connect", user_connection_requests_path(user) %>
      <% end %>
    </li>
	<% end %>
</ul>